development:
  adapter: postgresql
  encoding: unicode
  database: simplebartab_development
  pool: 5
  username: simplebartab

test:
  adapter: postgresql
  encoding: unicode
  database: simplebartab_test
  pool: 5
  username: simplebartab
