development:
  adapter: postgresql
  encoding: unicode
  database: sibita_development
  pool: 5
  username: sibata

test:
  adapter: postgresql
  encoding: unicode
  database: sibata_test
  pool: 5
  username: sibata

production:
  adapter: postgresql
  encoding: unicode
  database: sibata_production
  pool: 5
  username: deploy
